/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "main.h"
#include "USART.h"
#include "GPIO.h"



USART_Config serial;


int main(void)
{
	MCU_Clock_Setup();
	USART_Config_Reset(&serial);

	serial.Port = USART1;
	serial.TX_Pin = USART1_TX_Pin.PA9;
	serial.RX_Pin = USART1_RX_Pin.PA10;
	serial.baudrate = 115200;

	USART_Init(&serial);










    /* Loop forever */
	for(;;);
}
